openapi: 3.0.0
info:
  title: La Book API
  description: API for la book university e-library , etc.
  version: 1.0.0
  contact:
    name: Support
    email: support@example.com
    url: https://example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:5500/api/v1

paths: {}

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: boolean
          example: "true"
        message:
          type: string
          example: "An error occurred"
security:
  - BearerAuth: []