-- AlterTable
ALTER TABLE "Borrows" ALTER COLUMN "returnDate" SET DEFAULT CURRENT_TIMESTAMP + INTERVAL '7 DAYS';

-- AlterTable
ALTER TABLE "Users" ADD COLUMN     "lastLogin" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
